"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, AlertTriangle, ArrowUpRight, BarChart3, Clock3, Database, Gauge, RefreshCw, Server, ShieldAlert, TimerReset } from "lucide-react";

type MonitorData = { generated_at: string; throughput: { minute: string; rows: number }[]; queue_depth: { batches: number; rows: number; active_workers: number; max_queue_wait_ms: number }; queue_status: string; qstash: { configured: boolean; pending: number; failed: number; dead_lettered: number; published_last_5m: number }; stage_latency: { stage: string; p50: number; p95: number; p99: number }[]; errors: { code: string; count: number }[]; slow_batches: { task_id: string; unit_id: string; duration_ms: number }[]; recent_tasks: { id: string; trace_id: string; file_name: string; status: string; processing_stage: string; total_rows: number; success_rows: number; failed_rows: number; created_at: string }[] };

const stageNames: Record<string, string> = { parse: "文件解析", rule: "规则引擎", validate: "SKU 校验", insert: "批量写入" };
const taskStatus: Record<string, string> = { pending: "等待", processing: "处理中", completed: "完成", partial_success: "部分成功", failed: "失败" };

export default function ImportMonitorPage() {
  const [data, setData] = useState<MonitorData | null>(null);
  const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (showRefreshing = true) => { if (showRefreshing) setRefreshing(true); try { const response = await fetch("/api/import-monitor/summary", { cache: "no-store" }); if (response.ok) setData(await response.json() as MonitorData); } finally { if (showRefreshing) setRefreshing(false); } }, []);
  useEffect(() => { const kickoff = window.setTimeout(() => void load(false), 0); const timer = window.setInterval(() => void load(false), 5000); return () => { window.clearTimeout(kickoff); window.clearInterval(timer); }; }, [load]);
  const maxThroughput = useMemo(() => Math.max(1, ...(data?.throughput.map((item) => item.rows) || [])), [data]);
  if (!data) return <div className="mx-auto max-w-7xl px-6 py-16 text-center text-[#86909c]">正在加载监控数据...</div>;

  return <div className="mx-auto max-w-7xl px-4 py-7 sm:px-6"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Operations / Import Runtime</p><h1 className="text-3xl font-bold tracking-tight text-[#1d2129]">导入监控台</h1><p className="mt-1 text-sm text-[#86909c]">用真实任务、批次性能日志和错误明细观察 V2 异步导入链路。</p></div><div className="flex items-center gap-3 text-xs text-[#86909c]"><span>更新时间 {new Date(data.generated_at).toLocaleTimeString("zh-CN")}</span><button className="btn-outline" onClick={() => void load()} disabled={refreshing}><RefreshCw className={`h-4 w-4 ${refreshing ? "animate-spin" : ""}`} />刷新</button></div></div>
    {data.queue_status !== "healthy" && <div className={`alert mb-5 flex items-center gap-2 ${data.queue_status === "critical" ? "alert-danger" : "alert-warning"}`}><AlertTriangle className="h-5 w-5" />{data.queue_status === "critical" ? `队列不可用或存在失败消息：Outbox 失败 ${data.qstash.failed}，DLQ ${data.qstash.dead_lettered}。` : "队列积压已超过阈值，请检查 QStash 投递与数据库写入耗时。"}</div>}
    <div className="mb-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Signal icon={<Gauge />} label="近 5 分钟入库" value={`${data.throughput.reduce((s, item) => s + item.rows, 0).toLocaleString()} 行`} note="按完成任务真实聚合" tone="teal" /><Signal icon={<Server />} label="队列积压" value={`${data.queue_depth.rows.toLocaleString()} 行`} note={`${data.queue_depth.batches} 个处理单元 · 等待 Pmax ${Math.round(data.queue_depth.max_queue_wait_ms / 1000)}s`} tone={data.queue_status === "healthy" ? "green" : "orange"} /><Signal icon={<ShieldAlert />} label="QStash / DLQ" value={`${data.qstash.failed} / ${data.qstash.dead_lettered}`} note={`待投 ${data.qstash.pending} · 近 5 分钟发布 ${data.qstash.published_last_5m}`} tone={data.queue_status === "critical" ? "red" : "green"} /><Signal icon={<TimerReset />} label="消费策略" value="1,000 行 / 批" note={`Flow Control 并发 4 · 活跃 ${data.queue_depth.active_workers}`} tone="blue" /></div>
    <div className="mb-5 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><section className="card"><SectionTitle icon={<BarChart3 />} title="实时吞吐量" kicker="LAST 5 MINUTES" /><div className="mt-6 flex h-52 items-end gap-3 border-b border-[#e5e6eb] px-2 pb-0">{data.throughput.length === 0 ? <Empty label="完成任务后将显示每分钟入库行数" /> : data.throughput.map((item) => <div className="group flex h-full flex-1 flex-col items-center justify-end gap-2" key={item.minute}><div className="w-full max-w-16 rounded-t-lg bg-[#0fc6c2] transition-all group-hover:bg-[#0b6e6e]" style={{ height: `${Math.max(8, item.rows / maxThroughput * 88)}%` }} title={`${item.minute}: ${item.rows} 行`} /><span className="text-[11px] text-[#86909c]">{item.minute}</span></div>)}</div><p className="mt-3 text-xs text-[#86909c]">目标基线：10,000 单 / 分钟 · 数据来自 import_tasks 和批次日志真实聚合</p></section><section className="card"><SectionTitle icon={<Database />} title="队列健康度" kicker="QUEUE DEPTH" /><div className="mt-7 flex items-center gap-5"><div className={`relative flex h-32 w-32 flex-shrink-0 items-center justify-center rounded-full border-[14px] ${data.queue_status === "healthy" ? "border-[#b7ebc3]" : "border-[#ffe4ba]"}`}><div className="text-center"><p className="text-2xl font-semibold">{data.queue_depth.batches}</p><p className="text-[11px] text-[#86909c]">批次等待</p></div></div><div className="space-y-3 text-sm"><p className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#17c964]" />活跃 Worker <strong>{data.queue_depth.active_workers} / 4</strong></p><p className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#0fc6c2]" />积压行数 <strong>{data.queue_depth.rows.toLocaleString()}</strong></p><p className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#f5a524]" />预警阈值 <strong>5,000</strong></p></div></div></section></div>
    <div className="mb-5 grid gap-5 lg:grid-cols-[1.2fr_1fr]"><section className="card"><SectionTitle icon={<Clock3 />} title="阶段耗时分布" kicker="P50 / P95 / P99 · MS" /><div className="mt-4 overflow-x-auto"><table className="table-styled"><thead><tr><th>阶段</th><th>P50</th><th>P95</th><th>P99</th><th>判断</th></tr></thead><tbody>{data.stage_latency.map((row) => <tr key={row.stage}><td className="font-medium">{stageNames[row.stage] || row.stage}</td><td>{row.p50}</td><td>{row.p95}</td><td className="font-semibold text-[#0b6e6e]">{row.p99}</td><td>{row.p99 > 1000 ? <span className="tag tag-orange">需关注</span> : <span className="tag tag-green">稳定</span>}</td></tr>)}</tbody></table></div></section><section className="card"><SectionTitle icon={<AlertTriangle />} title="错误类型分布" kicker="ERROR CODES" /><div className="mt-4 space-y-3">{data.errors.length === 0 ? <Empty label="暂无错误" /> : data.errors.slice(0, 6).map((item, index) => <div key={item.code}><div className="mb-1 flex justify-between text-sm"><span><span className="mr-2 font-mono text-[#cf1322]">{item.code}</span>{errorName(item.code)}</span><strong>{item.count}</strong></div><div className="h-2 rounded-full bg-[#f0f0f0]"><div className="h-full rounded-full bg-[#cf1322]" style={{ width: `${Math.max(8, item.count / Math.max(1, data.errors[0].count) * 100)}%`, opacity: 1 - index * .1 }} /></div></div>)}</div></section></div>
    <div className="grid gap-5 lg:grid-cols-[1fr_1fr]"><section className="card"><SectionTitle icon={<ArrowUpRight />} title="慢批次 TOP 10" kicker="PERFORMANCE LOG" /><div className="mt-3 divide-y divide-[#f0f0f0]">{data.slow_batches.length === 0 ? <Empty label="暂无性能日志" /> : data.slow_batches.map((item) => <div className="flex items-center justify-between py-3 text-sm" key={`${item.task_id}-${item.unit_id}`}><span><span className="mr-3 font-mono text-xs text-[#86909c]">{item.unit_id}</span><Link className="text-[#0b6e6e] hover:underline" href={`/import-tasks/${item.task_id}`}>{item.task_id.slice(0, 8)}...</Link></span><strong>{item.duration_ms} ms</strong></div>)}</div></section><section className="card"><SectionTitle icon={<Activity />} title="最近导入任务" kicker="TASK STREAM" /><div className="mt-3 divide-y divide-[#f0f0f0]">{data.recent_tasks.map((task) => <RecentTask key={task.id} task={task} />)}</div></section></div>
  </div>;
}
function RecentTask({ task }: { task: MonitorData["recent_tasks"][number] }) { return <article className="py-3 text-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-medium text-[#1d2129]">{task.file_name}</span><span className={`tag ${task.status === "failed" ? "tag-red" : task.status === "completed" ? "tag-green" : task.status === "partial_success" ? "tag-orange" : "tag-teal"}`}>{taskStatus[task.status] || task.status}</span></div><p className="mt-1 text-xs text-[#86909c]">{new Date(task.created_at).toLocaleString("zh-CN", { hour12: false })} · 成功 {task.success_rows.toLocaleString()} / 失败 {task.failed_rows.toLocaleString()}</p><dl className="mt-2 grid gap-1 rounded-lg bg-[#f7f8fa] px-3 py-2 font-mono text-[11px] leading-5 text-[#4e5969]"><div className="flex min-w-0 gap-2"><dt className="w-14 flex-none text-[#86909c]">task_id</dt><dd className="truncate" title={task.id}>{task.id}</dd></div><div className="flex min-w-0 gap-2"><dt className="w-14 flex-none text-[#86909c]">trace_id</dt><dd className="truncate" title={task.trace_id}>{task.trace_id}</dd></div></dl></div><div className="flex flex-none flex-col gap-2 sm:flex-row"><Link className="btn-outline !px-3 !py-1.5 text-xs" href={`/import-tasks/${task.id}`}>任务详情</Link><Link className="btn-primary !px-3 !py-1.5 text-xs" href={`/traces/${task.trace_id}`}>Trace 链路</Link></div></div></article>; }
function Signal({ icon, label, value, note, tone }: { icon: React.ReactNode; label: string; value: string; note: string; tone: string }) { return <div className="card"><div className={`mb-4 flex h-9 w-9 items-center justify-center rounded-lg ${tone === "red" ? "bg-[#fff1f0] text-[#cf1322]" : tone === "orange" ? "bg-[#fff7e8] text-[#d97b00]" : tone === "green" ? "bg-[#e8faf0] text-[#17c964]" : tone === "blue" ? "bg-[#e6f1fb] text-[#185fa5]" : "bg-[#e8fafa] text-[#0b6e6e]"}`}>{icon}</div><p className="text-xs text-[#86909c]">{label}</p><p className="mt-1 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-[#86909c]">{note}</p></div>; }
function SectionTitle({ icon, title, kicker }: { icon: React.ReactNode; title: string; kicker: string }) { return <div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#e8fafa] text-[#0b6e6e]">{icon}</div><div><p className="eyebrow">{kicker}</p><h2 className="text-lg font-semibold">{title}</h2></div></div>; }
function Empty({ label }: { label: string }) { return <div className="flex flex-1 items-center justify-center text-sm text-[#86909c]">{label}</div>; }
function errorName(code: string) { return ({ E001: "SKU 不存在", E002: "必填字段缺失", E003: "电话格式错误", E004: "数量异常", E005: "外部编码重复", E006: "规则映射失败", E007: "数据库写入失败" } as Record<string, string>)[code] || "系统错误"; }
