"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, CircleAlert, Clock3, Loader2, RadioTower } from "lucide-react";

type TraceEvent = { id: string; task_id: string; unit_id: string | null; event_name: string; event_status: string; message: string; metadata: Record<string, unknown> | null; occurred_at: string };
const labels: Record<string, string> = { ImportTaskCreated: "任务创建", OutboxDispatched: "Outbox 投递", ImportBatchStarted: "批次开始", ImportBatchSucceeded: "批次完成", ImportBatchFailed: "批次失败", ImportTaskDegraded: "SKU 校验降级", ImportTaskCompleted: "任务完成", ImportTaskPartialSuccess: "任务部分成功" };

export default function TracePage({ params }: { params: Promise<{ traceId: string }> }) {
  const [traceId, setTraceId] = useState(""); const [events, setEvents] = useState<TraceEvent[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { params.then(({ traceId: id }) => { setTraceId(id); fetch(`/api/traces/${id}`, { cache: "no-store" }).then((response) => response.json()).then((data: { events: TraceEvent[] }) => { setEvents(data.events || []); setLoading(false); }); }); }, [params]);
  return <div className="mx-auto max-w-4xl px-4 py-7 sm:px-6"><Link href="/import-monitor" className="btn-ghost mb-4 gap-1 px-0"><ArrowLeft className="h-4 w-4" />返回监控台</Link><div className="mb-7 flex items-start gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#e8fafa] text-[#0b6e6e]"><RadioTower className="h-6 w-6" /></div><div><p className="eyebrow">Trace Timeline</p><h1 className="text-2xl font-bold">链路追踪时间线</h1><p className="mt-1 break-all font-mono text-xs text-[#86909c]">{traceId}</p></div></div>{loading ? <div className="card py-12 text-center text-[#86909c]"><Loader2 className="mx-auto mb-2 h-7 w-7 animate-spin" />正在读取时间线...</div> : events.length === 0 ? <div className="card py-12 text-center text-[#86909c]">暂无 Trace 事件</div> : <div className="relative ml-3 border-l-2 border-[#d0e8e8] pl-8">{events.map((event, index) => <div className="relative mb-6 last:mb-0" key={event.id}><span className={`absolute -left-[43px] top-1 flex h-6 w-6 items-center justify-center rounded-full border-4 border-[#f7f8fa] ${event.event_status === "failed" ? "bg-[#cf1322] text-white" : event.event_status === "warning" ? "bg-[#f5a524] text-white" : "bg-[#0fc6c2] text-white"}`}>{event.event_status === "failed" ? <CircleAlert className="h-3 w-3" /> : <CheckCircle2 className="h-3 w-3" />}</span><div className="card !p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><span className="font-semibold">{labels[event.event_name] || event.event_name}</span>{event.unit_id && <span className="ml-2 font-mono text-xs text-[#86909c]">{event.unit_id}</span>}</div><span className="flex items-center gap-1 text-xs text-[#86909c]"><Clock3 className="h-3 w-3" />{new Date(event.occurred_at).toLocaleString("zh-CN")}</span></div><p className={`mt-2 text-sm ${event.event_status === "failed" ? "text-[#cf1322]" : event.event_status === "warning" ? "text-[#d97b00]" : "text-[#4e5969]"}`}>{event.message}</p>{event.metadata && <pre className="mt-3 overflow-auto rounded bg-[#f7f8fa] p-3 text-[11px] text-[#86909c]">{JSON.stringify(event.metadata, null, 2)}</pre>}</div>{index < events.length - 1 && <div className="absolute -bottom-6 left-0 text-[10px] text-[#b4b9c2]">↓</div>}</div>)}</div>}</div>;
}
